# Generated by Django 3.1 on 2025-06-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
