# Generated by Django 3.1 on 2025-06-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='episodes_count',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
