# Generated by Django 3.1 on 2025-06-01 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0003_anime_episodes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnimeProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_episodes', models.PositiveIntegerField(default=0)),
                ('current_episode', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('watching', 'Смотрю'), ('completed', 'Просмотрено'), ('planned', 'В планах')], default='watching', max_length=20)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
